# This is the docker compose file which runs all the services
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka_network
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://172.23.0.3:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CREATE_TOPICS: "emails:3:1,predictions:3:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # emails-consumer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.Consumer
  #   networks:
  #     - kafka_network
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   ports:
  #     - 81:81

  # emails-deleter:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.Deleter
  #   networks:
  #     - kafka_network
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   ports:
  #     - 82:82
  
  # emails-producer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.Producer
  #   networks:
  #     - kafka_network
  #   depends_on:
  #     - emails-consumer
  #     - emails-deleter
  #     - kafka
  #     - zookeeper
  #   ports:
  #     - 80:80
  
  unified:
    build:
      context: .
      dockerfile: Dockerfile.Unified
    networks:
      - kafka_network
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 80:80


networks:
  kafka_network:
    name: kafka_network_test